# -*- coding: utf-8 -*-
"""Safelend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpuVhelgqu6hpZSh-gxDWTKhbAowc6hj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('credit_risk_dataset.csv')

print(df.head())

print(df.shape)
print(df.dtypes)

print(df.info())

print(df.describe())

print(df.isnull().sum())

df.duplicated().sum()

print(df.dtypes)

# 7. EDA / Data Understanding

# Unique values in categorical columns
print(df['person_home_ownership'].unique())
print(df['loan_intent'].unique())
print(df['loan_grade'].unique())
print(df['cb_person_default_on_file'].unique())

# Target distribution
print(df['loan_status'].value_counts())
print(df['loan_status'].value_counts(normalize=True))

# Target Distribution
plt.figure(figsize=(6,5))
sns.countplot(data=df, x='loan_status', palette=['#4CAF50', '#E74C3C'])
plt.title('Loan Status Distribution')
plt.xlabel('Loan Status (0 = No Default, 1 = Default)')
plt.ylabel('Count')
plt.show()

# Numerical Distributions
num_cols = ['person_age', 'person_income', 'person_emp_length', 'loan_amnt', 'loan_int_rate', 'loan_percent_income']

df[num_cols].hist(figsize=(12,8), bins=30, color='#3498DB')
plt.tight_layout()
plt.show()

# Boxplots for outliers
fig, axes = plt.subplots(2, 3, figsize=(15,8))

sns.boxplot(y=df['person_age'], ax=axes[0,0], color='#E67E22')
sns.boxplot(y=df['person_income'], ax=axes[0,1], color='#E67E22')
sns.boxplot(y=df['person_emp_length'], ax=axes[0,2], color='#E67E22')
sns.boxplot(y=df['loan_amnt'], ax=axes[1,0], color='#9B59B6')
sns.boxplot(y=df['loan_int_rate'], ax=axes[1,1], color='#9B59B6')
sns.boxplot(y=df['loan_percent_income'], ax=axes[1,2], color='#9B59B6')

plt.tight_layout()
plt.show()

# Default rate by loan grade
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='loan_grade', hue='loan_status', order=['A','B','C','D','E','F','G'], palette=['#4CAF50','#E74C3C'])
plt.title('Loan Status by Loan Grade')
plt.xlabel('Loan Grade')
plt.ylabel('Count')
plt.show()

# Default rate by loan intent
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='loan_intent', hue='loan_status', palette=['#4CAF50','#E74C3C'])
plt.title('Loan Status by Loan Intent')
plt.xlabel('Loan Intent')
plt.ylabel('Count')
plt.xticks(rotation=20)
plt.show()

# Correlation heatmap
plt.figure(figsize=(10,7))
correlation = df.corr(numeric_only=True)
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

print(df.columns)

# 10. Handle Missing Values
df['person_emp_length'] = df['person_emp_length'].fillna(df['person_emp_length'].median())
df['loan_int_rate'] = df['loan_int_rate'].fillna(df['loan_int_rate'].median())

print(df.isnull().sum())

# 11. Remove Duplicates
df = df.drop_duplicates()

print(df.duplicated().sum())
print(df.shape)

# 12. Separate Features and Target
X = df.drop('loan_status', axis=1)
y = df['loan_status']

# 13. Identify Numerical and Categorical Columns
num_cols = ['person_age', 'person_income', 'person_emp_length', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length']
cat_cols = ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']

print(X.shape)
print(y.shape)

# 14. Handle Outliers
print("Age > 100:", (X['person_age'] > 100).sum())
print("Employment length > age:", (X['person_emp_length'] > X['person_age']).sum())

X = X[X['person_age'] <= 100]
X = X[X['person_emp_length'] <= X['person_age']]
y = y[X.index]

print(X.shape)
print(y.shape)

from sklearn.preprocessing import LabelEncoder

# Log transform on income (تقليل الانحراف)
X['person_income'] = np.log1p(X['person_income'])

# Label Encoding لـ loan_grade
le = LabelEncoder()
X['loan_grade'] = le.fit_transform(X['loan_grade'])

# One-Hot Encoding للباقي
X = pd.get_dummies(X, columns=['person_home_ownership', 'loan_intent', 'cb_person_default_on_file'], drop_first=True)

print(X.shape)
print(X.columns)

from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=10)

X_selected = selector.fit_transform(X, y)

selected_features = X.columns[selector.get_support()]

print("Selected Features:")
print(selected_features)

print("New X shape:", X_selected.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled.shape)
print(X_test_scaled.shape)

print("Final shapes:")
print("X_train_scaled:", X_train_scaled.shape)
print("X_test_scaled:", X_test_scaled.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    class_weight='balanced',
    random_state=42
)

rf_model.fit(X_train_scaled, y_train)

y_pred_rf = rf_model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))

print(classification_report(y_test, y_pred_rf))

from xgboost import XGBClassifier

# حساب نسبة الموازنة يدويًا لـ XGBoost
scale = (y_train == 0).sum() / (y_train == 1).sum()

# Train
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    scale_pos_weight=scale,
    random_state=42,
    eval_metric='logloss'
)
xgb_model.fit(X_train_scaled, y_train)

# Predict
y_pred_xgb = xgb_model.predict(X_test_scaled)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall:", recall_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0]
}

xgb_grid = GridSearchCV(
    XGBClassifier(scale_pos_weight=scale, random_state=42, eval_metric='logloss'),
    param_grid,
    scoring='f1',
    cv=3,
    n_jobs=-1
)

xgb_grid.fit(X_train_scaled, y_train)

print("Best Parameters:", xgb_grid.best_params_)
print("Best F1 Score (CV):", xgb_grid.best_score_)

# أفضل موديل XGBoost بعد الضبط
best_xgb = xgb_grid.best_estimator_

y_pred_best_xgb = best_xgb.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_best_xgb))
print("Precision:", precision_score(y_test, y_pred_best_xgb))
print("Recall:", recall_score(y_test, y_pred_best_xgb))
print("F1 Score:", f1_score(y_test, y_pred_best_xgb))
print(classification_report(y_test, y_pred_best_xgb))

param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10]
}

rf_grid = GridSearchCV(
    RandomForestClassifier(class_weight='balanced', random_state=42),
    param_grid_rf,
    scoring='f1',
    cv=3,
    n_jobs=-1
)

rf_grid.fit(X_train_scaled, y_train)

print("Best Parameters:", rf_grid.best_params_)
print("Best F1 Score (CV):", rf_grid.best_score_)

best_rf = rf_grid.best_estimator_

y_pred_best_rf = best_rf.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_best_rf))
print("Precision:", precision_score(y_test, y_pred_best_rf))
print("Recall:", recall_score(y_test, y_pred_best_rf))
print("F1 Score:", f1_score(y_test, y_pred_best_rf))
print(classification_report(y_test, y_pred_best_rf))

final_model = best_xgb

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred_best_xgb)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['No Default', 'Default']
)

disp.plot(cmap='Greens')
plt.title('Confusion Matrix - Final XGBoost Model')  # ده بيستخدم matplotlib
plt.show()

results = pd.DataFrame({
    'Model': ['Random Forest', 'XGBoost (Tuned)'],
    'Accuracy': [0.9128, 0.9304],
    'Precision': [0.8273, 0.8746],
    'Recall': [0.7602, 0.7962],
    'F1 Score': [0.7924, 0.8335]
})

results_melted = results.melt(
    id_vars='Model',
    var_name='Metric',
    value_name='Score'
)

plt.figure(figsize=(12,6))

sns.barplot(
    data=results_melted,
    x='Metric',
    y='Score',
    hue='Model',
    palette='viridis'
)

plt.title('Model Comparison Across Metrics')
plt.ylim(0, 1)
plt.legend(
    title='Model',
    bbox_to_anchor=(1.02, 1),
    loc='upper left'
)

plt.tight_layout()
plt.show()

importances = best_xgb.feature_importances_
feature_names = X.columns

feat_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values('Importance', ascending=False)

plt.figure(figsize=(10,8))
sns.barplot(data=feat_df, x='Importance', y='Feature', palette='viridis')
plt.title('Feature Importance - XGBoost Model')
plt.xlabel('Importance Score')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

print(feat_df)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_train_scaled)

plt.figure(figsize=(9,7))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=y_train, palette=['#4CAF50', '#E74C3C'], alpha=0.5)
plt.title('PCA - 2D Visualization of Loan Status')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(title='Loan Status', labels=['No Default', 'Default'])
plt.show()

print("Explained Variance Ratio:", pca.explained_variance_ratio_)

from sklearn.cluster import KMeans

# اختيار أعمدة مالية بس (من غير الهدف) لعمل التقسيم عليها
cluster_cols = ['person_age', 'person_income', 'loan_amnt', 'loan_percent_income', 'loan_int_rate']
X_cluster = X_train[cluster_cols]

# Scaling خاص بيهم بس
from sklearn.preprocessing import StandardScaler
cluster_scaler = StandardScaler()
X_cluster_scaled = cluster_scaler.fit_transform(X_cluster)

# K-Means بـ 4 مجموعات
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_cluster_scaled)

# إضافة نتيجة الـ cluster لجدول مؤقت مع الهدف الحقيقي (y_train) عشان نحلل بس، مش للتدريب
segment_df = X_cluster.copy()
segment_df['Cluster'] = clusters
segment_df['loan_status'] = y_train.values

# نسبة التعثر الفعلية في كل مجموعة
default_rate_by_cluster = segment_df.groupby('Cluster')['loan_status'].mean().sort_values(ascending=False)
print(default_rate_by_cluster)

# متوسط كل عمود في كل Cluster
cluster_profile = segment_df.groupby('Cluster')[cluster_cols].mean()
print(cluster_profile)

plt.figure(figsize=(9,7))
sns.scatterplot(
    x=segment_df['person_income'],
    y=segment_df['loan_percent_income'],
    hue=segment_df['Cluster'],
    palette='Set2',
    alpha=0.6
)
plt.title('Customer Segments by Income & Loan-to-Income Ratio')
plt.xlabel('Income')
plt.ylabel('Loan Percent of Income')
plt.legend(title='Cluster')
plt.show()

